import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import logo from '../assets/logo_marentreefacile.png';
import Footer from '../components/Footer';
import { useCart } from '../CartContext';
import { formatPrice } from '../products';

const shippingOptions = { standard: { label: 'Standard à domicile', price: 2500 }, relais: { label: 'Point relais', price: 1500 }, express: { label: 'Express', price: 7500 } };

export default function CartPage() {
  const { pathname } = useLocation(); const checkout = pathname === '/paiement';
  const { items, updateQuantity, removeItem, clearCart } = useCart();
  const [shipping, setShipping] = useState('standard'); const [details, setDetails] = useState({ email: '', firstName: '', lastName: '', address: '', city: '' }); const [error, setError] = useState('');
  const subtotal = items.reduce((sum, item) => sum + item.price * item.quantity, 0); const delivery = shippingOptions[shipping].price; const total = subtotal + delivery;
  const change = (event) => setDetails({ ...details, [event.target.name]: event.target.value });
  const order = () => { if (Object.values(details).some((value) => !value.trim()) || !details.email.includes('@')) { setError('Veuillez compléter vos coordonnées avant de confirmer.'); return; } const lines = items.map((item) => `- ${item.name} x${item.quantity}: ${formatPrice(item.price * item.quantity)}`).join('\n'); window.open(`https://wa.me/2250700000000?text=${encodeURIComponent(`Bonjour, je souhaite commander :\n${lines}\nLivraison : ${shippingOptions[shipping].label} (${formatPrice(delivery)})\nTotal : ${formatPrice(total)}\nClient : ${details.firstName} ${details.lastName}, ${details.address}, ${details.city}.`)}`, '_blank', 'noopener,noreferrer'); };
  if (!checkout) return <><main className="min-h-screen bg-background-light"><div className="max-w-7xl mx-auto p-4 sm:p-8"><h1 className="text-3xl font-bold mb-8">Mon panier</h1>{items.length === 0 ? <div className="bg-white rounded-xl p-10 text-center"><p className="mb-4">Votre panier est vide.</p><Link className="bg-primary text-white px-5 py-3 rounded-lg font-bold" to="/catalogue">Découvrir le catalogue</Link></div> : <div className="grid lg:grid-cols-3 gap-8"><section className="lg:col-span-2 space-y-4">{items.map((item) => <article key={item.id} className="bg-white rounded-xl p-4 flex gap-4 items-center"><img src={item.image} alt="" className="w-20 h-20 object-cover rounded-lg"/><div className="flex-1"><Link to={`/produit/${item.id}`} className="font-bold hover:text-primary">{item.name}</Link><p className="text-primary font-bold">{formatPrice(item.price)}</p></div><div className="flex border rounded"><button type="button" onClick={() => updateQuantity(item.id, item.quantity - 1)} className="px-3">−</button><span className="px-3 py-1">{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.id, item.quantity + 1)} className="px-3">+</button></div><button type="button" onClick={() => removeItem(item.id)} className="text-red-600" aria-label={`Retirer ${item.name}`}>Supprimer</button></article>)}</section><aside className="bg-white rounded-xl p-6 h-fit"><h2 className="text-xl font-bold mb-5">Résumé</h2><div className="flex justify-between mb-4"><span>Sous-total</span><b>{formatPrice(subtotal)}</b></div><p className="text-sm text-slate-500 mb-5">Les frais de livraison sont calculés au paiement.</p><Link to="/paiement" className="block text-center bg-primary text-white py-3 rounded-xl font-bold">Passer au paiement</Link></aside></div>}</div></main><Footer /></>;
  return <main className="min-h-screen bg-background-light"><header className="bg-white border-b"><div className="max-w-7xl mx-auto px-4 h-16 flex justify-between items-center"><img src={logo} alt="MaRentreeFacile" className="h-10"/><Link to="/panier" className="text-primary">← Retour au panier</Link></div></header><div className="max-w-6xl mx-auto p-4 sm:p-8 grid lg:grid-cols-3 gap-8"><section className="lg:col-span-2"><h1 className="text-3xl font-bold mb-6">Finalisez votre commande</h1>{items.length === 0 ? <p>Votre panier est vide. <Link className="text-primary" to="/catalogue">Ajouter des produits</Link></p> : <><div className="bg-white p-6 rounded-xl space-y-4"><h2 className="font-bold text-lg">Informations de livraison</h2>{[['email','E-mail','email'],['firstName','Prénom','text'],['lastName','Nom','text'],['address','Adresse','text'],['city','Ville','text']].map(([name,label,type]) => <label key={name} className="block"><span className="text-sm font-medium">{label}</span><input required name={name} type={type} value={details[name]} onChange={change} className="mt-1 w-full rounded-lg border p-3" /></label>)}</div><div className="bg-white p-6 rounded-xl mt-6"><h2 className="font-bold text-lg mb-3">Livraison</h2>{Object.entries(shippingOptions).map(([key, option]) => <label key={key} className="flex justify-between p-3 border rounded-lg mb-2 cursor-pointer"><span><input className="mr-2" type="radio" name="shipping" checked={shipping === key} onChange={() => setShipping(key)} />{option.label}</span><b>{formatPrice(option.price)}</b></label>)}</div>{error && <p className="mt-4 text-red-600">{error}</p>}</>}</section><aside className="bg-white rounded-xl p-6 h-fit"><h2 className="font-bold text-xl mb-4">Résumé</h2>{items.map((item) => <div className="flex justify-between text-sm mb-2" key={item.id}><span>{item.name} × {item.quantity}</span><b>{formatPrice(item.price * item.quantity)}</b></div>)}<hr className="my-4"/><div className="flex justify-between"><span>Sous-total</span><b>{formatPrice(subtotal)}</b></div><div className="flex justify-between mt-2"><span>Livraison</span><b>{formatPrice(delivery)}</b></div><div className="flex justify-between text-lg mt-4"><b>Total</b><b className="text-primary">{formatPrice(total)}</b></div><button disabled={!items.length} type="button" onClick={order} className="w-full mt-6 bg-primary disabled:bg-slate-300 text-white py-3 rounded-xl font-bold">Confirmer via WhatsApp</button>{items.length > 0 && <button type="button" onClick={clearCart} className="w-full mt-3 text-sm text-slate-500">Vider le panier</button>}</aside></div></main>;
}
