import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import Footer from '../components/Footer';
import { useCart } from '../CartContext';
import { formatPrice, products } from '../products';

export default function CataloguePage() {
  const [category, setCategory] = useState('Toutes'); const [brand, setBrand] = useState('Toutes'); const [sortBy, setSortBy] = useState('recent'); const [maxPrice, setMaxPrice] = useState(50000);
  const { addItem } = useCart();
  const categories = ['Toutes', ...new Set(products.map((item) => item.category))]; const brands = ['Toutes', ...new Set(products.map((item) => item.brand))];
  const displayed = useMemo(() => products.filter((item) => (category === 'Toutes' || item.category === category) && (brand === 'Toutes' || item.brand === brand) && item.price <= maxPrice).sort((a, b) => sortBy === 'price-asc' ? a.price - b.price : sortBy === 'price-desc' ? b.price - a.price : sortBy === 'rating' ? b.rating - a.rating : a.id - b.id), [category, brand, maxPrice, sortBy]);
  return <div className="bg-background-light min-h-screen"><main className="max-w-7xl mx-auto px-4 py-8"><nav className="text-sm text-slate-500 mb-6"><Link to="/">Accueil</Link> / Fournitures scolaires</nav><h1 className="text-3xl font-bold mb-8">Fournitures scolaires</h1><div className="grid lg:grid-cols-[16rem_1fr] gap-8"><aside className="bg-white rounded-xl p-5 h-fit space-y-5"><div className="flex justify-between"><h2 className="font-bold">Filtres</h2><button type="button" onClick={() => { setCategory('Toutes'); setBrand('Toutes'); setMaxPrice(50000); }} className="text-primary text-sm">Réinitialiser</button></div><label className="block text-sm font-medium">Catégorie<select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-1 w-full border rounded p-2">{categories.map((value) => <option key={value}>{value}</option>)}</select></label><label className="block text-sm font-medium">Marque<select value={brand} onChange={(event) => setBrand(event.target.value)} className="mt-1 w-full border rounded p-2">{brands.map((value) => <option key={value}>{value}</option>)}</select></label><label className="block text-sm font-medium">Prix maximum : {formatPrice(maxPrice)}<input type="range" min="0" max="50000" step="500" value={maxPrice} onChange={(event) => setMaxPrice(Number(event.target.value))} className="mt-2 w-full accent-primary" /></label></aside><section><div className="flex flex-wrap justify-between gap-3 mb-6"><p>{displayed.length} produit{displayed.length > 1 ? 's' : ''} trouvé{displayed.length > 1 ? 's' : ''}</p><label className="text-sm">Trier par <select value={sortBy} onChange={(event) => setSortBy(event.target.value)} className="border rounded p-2"><option value="recent">Plus récents</option><option value="price-asc">Prix croissant</option><option value="price-desc">Prix décroissant</option><option value="rating">Mieux notés</option></select></label></div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-6">{displayed.map((product) => <article key={product.id} className="bg-white rounded-xl overflow-hidden border flex flex-col"><Link to={`/produit/${product.id}`}><img src={product.image} alt={product.name} className="w-full aspect-square object-cover" /></Link><div className="p-4 flex-1 flex flex-col"><p className="text-xs text-slate-500">{product.category} · {product.brand}</p><Link to={`/produit/${product.id}`} className="font-bold mt-1 hover:text-primary">{product.name}</Link><p className="mt-2 text-primary font-bold">{formatPrice(product.price)}</p><button type="button" onClick={() => addItem(product)} className="mt-4 bg-primary text-white rounded-lg py-2 font-bold">Ajouter au panier</button></div></article>)}</div>{!displayed.length && <p className="bg-white rounded-xl p-6">Aucun produit ne correspond à vos filtres.</p>}</section></div></main><Footer /></div>;
}
