import { useState } from 'react';
import { Link } from 'react-router-dom';
import Footer from '../components/Footer';
import { useCart } from '../CartContext';
import { formatPrice, products } from '../products';

export default function KitsPage() {
  const [viewMode, setViewMode] = useState('grid'); const { addItem } = useCart(); const kits = products.filter((product) => product.category === 'Kits');
  return <div className="bg-background-light min-h-screen"><main className="max-w-7xl mx-auto px-4 py-8"><nav className="text-sm text-slate-500 mb-6"><Link to="/">Accueil</Link> / Kits scolaires</nav><div className="flex flex-wrap justify-between gap-4 mb-8"><div><h1 className="text-3xl font-bold">Kits scolaires par classe</h1><p className="text-slate-600">Les indispensables regroupés pour une rentrée sereine.</p></div><div className="border rounded-lg p-1 bg-white"><button type="button" onClick={() => setViewMode('grid')} className={`px-4 py-2 rounded ${viewMode === 'grid' ? 'bg-primary text-white' : ''}`}>Grille</button><button type="button" onClick={() => setViewMode('list')} className={`px-4 py-2 rounded ${viewMode === 'list' ? 'bg-primary text-white' : ''}`}>Liste</button></div></div><div className={viewMode === 'grid' ? 'grid sm:grid-cols-2 lg:grid-cols-3 gap-6' : 'space-y-4'}>{kits.map((product) => <article key={product.id} className={`bg-white rounded-xl border overflow-hidden ${viewMode === 'list' ? 'sm:flex' : ''}`}><Link to={`/produit/${product.id}`} className={viewMode === 'list' ? 'sm:w-48 shrink-0' : ''}><img src={product.image} alt={product.name} className="w-full aspect-square object-cover" /></Link><div className="p-5 flex-1"><h2 className="font-bold text-xl">{product.name}</h2><p className="text-slate-500 text-sm mt-1">{product.items}</p><p className="text-primary text-xl font-bold mt-4">{formatPrice(product.price)}</p><div className="flex gap-3 mt-4"><Link to={`/produit/${product.id}`} className="border border-primary text-primary px-4 py-2 rounded-lg">Détails</Link><button type="button" onClick={() => addItem(product)} className="bg-primary text-white px-4 py-2 rounded-lg font-bold">Ajouter</button></div></div></article>)}</div></main><Footer /></div>;
}
